linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - gochecknoinits
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - text: "weak cryptographic primitive"
      linters:
        - gosec
