language: go

go:
  - 1.12.x
  - tip

before_install:
  - go get -t -v ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash) -t cee1976e-abef-4536-ba0f-bfef91d55a7c
